title: "CodeRcar's Site"
email: "matthew@botinabox.ca"
description: >- # this means to ignore newlines until "baseurl:"
 "The latest project from Bot-In-a-Box Educational Robotics"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://CodeRcar.botinabox.ca" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: botinaboxer
github_username:  botinaboxer

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

search_enabled: true
color_scheme: "nil"
aux_links:
  "Bot-In-a-Box's Website":
    - "https://botinabox.ca"

sass:
    style: compressed
    sass_dir: _sass

ga_tracking: UA-138686532-1
